Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jsilson Costa do Santos
// Descrição   : Extrutura de decisão escolha caso
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 09/09/2026
Var
   // Seção de Declarações das variáveis
   diadasemana:inteiro

Inicio

   escreval("Digite um número correspondente ao dia de sua semana")
   escolha(diadasemana)

   caso=1
      escreval("Você esta no Domingo!")
   caso=2
      escreval("Você esta na Segunda")
   caso=3
      escreval("Você esta na Segunda")
   caso=4
      escreval("Você esta na Segunda")
   caso=5
      escreval("Você esta na Segunda")
   caso=6
      escreval("Você esta na Segunda")
   caso=7
      escreval("Você esta na Segunda")
   outrocaso
      ("Não a dias da semana correspondente")

   fimescolha
fimescolha
fimescolha
fimescolha
fimescolha
fimescolha
fimescolha








Fimalgoritmo