Algoritmo "lendoValoresEmostrandoOMeior"
// Disciplina   : [Linguagem e Lógica de Programação com Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler três valor e escrever o maior deles.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 07/08/2026
Var

primeironumero:inteiro
segundonumero:inteiro
terceironumero:inteiro

Inicio

escreval("Digite um número")
leia(primeironumero)
escreval("Digite segundo número")
leia(segundonumero)
escreval("Digite o terceiro número")
leia(terceironumero)

se (primeironumero > segundonumero) e (primeironumero > terceironumero) entao
escreval("O maior número entre eles é:", primeironumero)
senao
se (segundonumero>primeironumero) e (segundonumero>terceironumero) entao
escreval("O maior número entre eles é:", segundonumero)
senao
se (terceironumero>primeironumero) e (terceironumero>segundonumero) entao
escreval("O maior número entre eles é:", terceironumero)
fimse
fimse
fimse




Fimalgoritmo