Algoritmo "convertendofahrenheitemcelcius"
// Disciplina   : [Linguagem e Lógica de Programação com Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Convertendo valor fahrenheit em celcius.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 02/09/2026

Var
fahrenheit:real
celcius:real

Inicio

escreval("Digite sua temperatura em graus fahrenheit")
leia(fahrenheit)

celcius<-(fahrenheit-32)*5/9
escreval("A temperatura em Celcius será:",celcius,"°C")


Fimalgoritmo

