Algoritmo "inversaodevalores"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor    : Jailson Costa dos Santos
// Descrição    : Trocar os valores deixando eles invertendos,bfazendo com que o
// valor que está em A passe para B e vice-versa.
// Autor(a)     : Agnes Pereira Rodrigues Catarino
// Data atual   : 28/08/2026
Var
a,b,c:inteiro

Inicio

a<-10
b<-20
c<-a+b
escreval("")
escreval(a,b)
c<-a
a<-b
b<-c
escreval(a,b)


Fimalgoritmo