Algoritmo "lendoDoisValores"
// Disciplina   : [Linguagem e Lógica de Programação com Javascript ]
// Professor    : Jailson Costa dos santos
// Descrição    : Lerdois valores e mostrar se eles são iguais ou qual dos
//valores é maior.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 08/08/2026
Var
 primeirovalor:inteiro
 segundovalor:inteiro

Inicio

escreval("Digite o primeiro número")
leia(primeirovalor)
escreval ("Digite o segundo número")
leia(segundovalor)

se primeirovalor=segundovalor entao
escreval("Os números são iguais")
senao
se primeirovalor>segundovalor entao
escreval ("O primeiro número é maior ")
senao segundovalor>primeirovalor
escreval("O segundo número é maior")
fimse
fimse

Fimalgoritmo