Algoritmo "analisedealgoritimos"
// Disciplina   : [Linguagem e Lógica de Programação com JavaSript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ver com qual valor o B fica após adicionar <5 a ele
// Autor(a)    : Agnes Pereira Rodirgues Catarino
// Data atual  : 31/08/2026
Var
A,B: Inteiro


Inicio
A<-10
B<-20
Escreva(B)
B<-5
Escreva (A,B)

//B começa a possuír apenas o valor 5, descartando a valor 20 ao qual possuia anteriormente.
Fimalgoritmo