Algoritmo "organizarValoresDeFormaCrescente"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   :Ler dois valores e organizalos de forma crescenete.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 06/09/2026
Var
primeirovalor:inteiro
segundovalor:inteiro

Inicio
escreval("Digite o valor e deixaremos de forma crescente!")
escreval("")
escreval("Digite um valor")
leia (primeirovalor)
escreval("Digite mais um valor")
leia (segundovalor)
escreval("")
se primeirovalor>segundovalor entao
escreval("Então o primeiro valor que vem é:",primeirovalor, " depois" ,segundovalor)
senao
escreval("Então o primeiro valor que vem é:",segundovalor," depois",primeirovalor)
fimse

Fimalgoritmo