Algoritmo "mostraroMaiorNumero"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Escrever dois valores e exibir o maior número entre eles que foi digitado.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 06/09/2026
Var
primeirovalor:real
segundovalor:real

Inicio
escreval("Digite um valor e veja qual deles é o maior")
escreval("")
escreval ("Digite um valor")
leia(primeirovalor)
escreval ("Digite outro valor")
leia(segundovalor)
se segundovalor>primeirovalor então
escreval("Entre os dois valores digitados", segundovalor,"  é o valor maior")
senao
escreval("Entre os dois valores digitado", primeirovalor," é o valor maior")
fimse

Fimalgoritmo