Algoritmo "calculodasareasdoretangulo"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa do Santos
// Descrição   : Calculando a área do retângulo.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 01/09/2026
Var
area:real
base:real
altura:real

Inicio
escreval("Me informe o valor da base de seu retângulo")
leia(base)
escreval("Me informe o valor da altura de seu retângulo")
leia(altura)
area<-base*altura/2
escreval("O valor de sua área do retângulo é:",area)
escreval("Pois somamos (base x altura) e dividimos o valor por 2")

Fimalgoritmo