Algoritmo "resulucaologicaComLetras"
// Disciplina   : [Linguagem e Lógica de Programação com javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Lidando com operadores lógicos.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 10/08/2026
Var

a,b,c:logico

Inicio
a<-verdadeiro
b<-verdadeiro
c<-falso

escreval("a) (A e B) ou (A xou B): ", (A e B) ou (A xou B))
escreval("b) (A ou B) e (A e C): ", (A ou B) e (A e C))
escreval("c) A ou C e B xou A e nao B: ", A ou C e B xou A e nao B)
Fimalgoritmo