Algoritmo "determinandoValor"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Ler um valor e escrever se é positivo, negativo ou igual a zero.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 07/09/2026

Var
valor:real

Inicio

escreval("Escreva um valor")
leia(valor)

se valor <0 entao
escreval("Este valor é negativo")
senao
se valor =0 entao
escreval("Este valor é igual a zero:", valor)
senao
escreval("Este valor é positivo", valor)
fimse
fimse

Fimalgoritmo