Algoritmo "somarIdadesDeDuasMulheresEdoisHomens"
// Disciplina   : [Linguagem e Lógica de Programação com JavasCript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcular a idade de dois homens e de duas mulheres, realizando a soma
// correspondente ao homem mais velho + a mulher mais nova e a mulher mais velha + homem mais novo.
// Autor(a)    : Agnes Pereira rodrigues Catarino
// Data atual  : 26/09/2026
Var

homemmaisnovo:inteiro
homemmaisvelho:inteiro
mulhermaisvelha:inteiro
mulhermaisnova: inteiro
soma: inteiro
soma2:inteiro

Inicio

escreval("Digite a idade de dois homens e duas mulheres distintas abaixo")
escreval("")
escreval("Digite a idade do homem mais velho ao qual você conheça")
leia (homemmaisvelho)
escreval("Digite a idade do homem mais novo ao qual você conheça")
leia (homemmaisnovo)
escreval("Digite a idade da mulher mais velha ao qual você conheça")
leia (mulhermaisvelha)
escreval("Digite a idade da mulher mais nova ao qual você conheça")
leia (mulhermaisnova)


soma<-(homemmaisvelho+mulhermaisnova)
soma2<-(homemmaisnovo*mulhermaisvelha)

escreval("")
escreval("A soma da idade do homem mais velho + a humlher mais nova será:",soma)
escreval("")
escreval("Já o produto, idade do homem mais novo X a mulher mais velha será:", soma2)

Fimalgoritmo