Algoritmo "mediageralaritmetica"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Media Geral aritimética do aluno.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 06/09/2026
Var
nota1:inteiro
nota2:inteiro
soma:real

Inicio
escreval("Qual foi a nota da atividade 1 do aluno?")
leia (nota1)
escreval("Qual foi a nota da atividade 2 do aluno")
leia(nota2)
soma<-(nota1+nota2)/2
se soma>=6 entao
escreval("O aluno é aprovado")
senao
escreval("O aluno é reprovado")
fimse

escreval("Pois o aluno tirou media geral aritimética de",soma)

Fimalgoritmo