Algoritmo "diferencaDevaloresSemParenteses"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Deixar o minímo de parenteses possível sem alterar o resultado.
// Autor(a)    : Agnes Pereira Rodrigues catarino
// Data atual  : 31/08/2026

var

a,b,c,d,e,f,g,h,i,j:real

inicio

a <- 6*(3+2)
b <- 2+6*(3+2)
c <- 2+3*6/(2+4)
d <- 2*8/(3+1)
e <- 3+(16-2)/(2*(9-2))
f <- 6/3+8/2
g <- (3+8/2)*4+3*2
h <- 6*3*3+6-10
i <- (10*8+3)*9
j <- -12*(-4)+3*(-4)

escreval("A = ", a)
escreval("B = ", b)
escreval("C = ", c)
escreval("D = ", d)
escreval("E = ", e)
escreval("F = ", f)
escreval("G = ", g)
escreval("H = ", h)
escreval("I = ", i)
escreval("J = ", j)

fimalgoritmo