Algoritmo "reincercaodevaloresoma"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Colocando um valor novo no B e o somando novamente
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 31/08/2026
Var
A,B,C:Inteiro


Inicio
 A<-30
 B<-20
 C<-A + B
 Escreva(C)
 B<-10
 Escreva (B,C)
 C<-A+B)
 Escreva (A,B,C)
 //B de 20 passa a valer 10, alterando o resultado das outras contas.
 //Por  passar a soma de C<-a+b na ultima fileira de 50 começar a valer 40.
 // Já que antes na primeira fileira, o valor A possuía 30, o valor B possuia 20, e o valor C sendo a soma do A+B, totalizando 50.
 // E na ultima fileira o valor B passa a possuír apenas 10, e o valor A continua com 30, Fazendo com que C some A30+B10, totalizando 40.
//O correndo então a alteração de valores nas contas, ao mudar o valor de B.
Fimalgoritmo