Algoritmo "numeroPositivoOuNegativo"
// Disciplina   : [Linguagem e Lógica de Programação com  Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Definir ao digitar um número se ele é positivo ou negativo>
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 06/08/2026
Var

valor:real

Inicio
escreval("Digite um valor para descobrir se ele é positivo ou negativo")
leia(valor)
se valor<=-1 entao
escreval("Este valor é negativo")
senao
escreval("Este valor é positivo")
fimse
Fimalgoritmo