Algoritmo "descobrirnumeroantecessor"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa do Santos
// Descrição   : Descobrir o número antecessor
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 01/09/2026
Var
valor:real
antecessor:caracter

Inicio
escreval ("Insira o numero ao qual você deseje descobrir seu antecessor")
leia(valor)
antecessor<-valor-1
escreval("o numero antecessor neste caso é:",antecessor)
escreval ("pois extraimos um numero dela")




Fimalgoritmo