Algoritmo "maiorEmenor"
// Disciplina   : [Linguagem e Lógica de Programação com Javascript]
// Professor   : Jailson Costa doss Santos
// Descrição   : Escrever se o número e ou não maior que 10.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 06/09/2026
Var
valor:real

Inicio
escreval("Digite um valor e descubra se ele e maior ou não")
leia (valor)
se valor>10 entao
escreval("E MAIOR QUE 10!")
senao
escreva("E MENOR QUE 10!")

fimse

Fimalgoritmo