Algoritmo "L01A"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Transformando Celscius em Fahrenheit.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 20/09/2026
Var
// Seção de Declarações das variáveis 

celcius:inteiro
fahrenheit:real

inicio

Escreval("Digite um número em Celcius e tranforme em fahrenheit")
leia(celcius)

fahrenheit<-(9*celcius+160)/5

escreval("Seu valor convertido em fahrenheit é: ", fahrenheit)



Fimalgoritmo