Algoritmo "L01B"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Convertendo o valor de fahrenheit para Celcius.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/09/2026
Var

fahrenheit:inteiro
celcius:real

Inicio

escreval("Digite um valor em Fahrenheit e converta para Celcius")
leia(fahrenheit)

celcius<-(fahrenheit-32)*(5/9)
escreval ("Sua temperatura em Celcius será:", celcius)



Fimalgoritmo