Algoritmo "L01C"
// Disciplina   : [Linguagem e Lógica de Programação com Javascript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Descorbir o volume de uma lata de óleo.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026
Var

raio, altura,volume: real

Inicio

escreval("Qual é o raio do óleo?")
leia(raio)
escreval("Qual é a altura deste óleo?")
leia (altura)

volume<-pi *(raio^2)*altura

escreval ("O valor de um volume de uma lata de óleo e de: ", volume)


Fimalgoritmo