Algoritmo "L01F"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos santos
// Descrição   : Inversão dos valores da letra A e B.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

a,b,c:inteiro

Inicio

escreval("Digite um valor a letra A")
leia (a)
escreval("Digite um valor a letra B")
leia (b)

c<-a
a<-b
b<-c

escreval("Viu como invertemos os valores? ",a,b)


Fimalgoritmo