Algoritmo "L01G"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos santos
// Descrição   : Realizar seis contas de multiplicação e seis contas de soma.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

a,b,c,d:inteiro
soma1,soma2,soma3,soma4,soma5,soma6:inteiro
multi1,multi2,multi3,multi4,multi5,multi6:inteiro
Inicio

escreval("Digite um valor a letra A")
leia (a)
escreval("Digite um valor a letra B")
leia (b)
escreval("Digite um valor a letra A")
leia (c)
escreval("Digite um valor a letra B")
leia (d)

soma1<-a+b
soma2<-a+c
soma3<-a+d
soma4<-b+c
soma5<-b+d
soma6<-c+d

multi1<-a*b
multi2<-a*c
multi3<-a*d
multi4<-b*c
multi5<-b*d
multi6<-c*d



escreval("O resultado da soma de a+b ", soma1)
escreval("O resultado da soma de a+c ", soma2)
escreval("O resultado da soma de a+d ", soma3)
escreval("O resultado da soma de b+c ", soma4)
escreval("O resultado da soma de b+d ", soma5)
escreval("O resultado da soma de c+d ", soma6)

escreval("O resultado de multiplicação de a+b ", multi1)
escreval("O resultado de multiplicação de a+c ", multi2)
escreval("O resultado de multiplicação de a+d ", multi3)
escreval("O resultado de multiplicação de b+c ", multi4)
escreval("O resultado de multiplicação de b+d ", multi5)
escreval("O resultado de multiplicação de c+d ", multi6)


Fimalgoritmo