Algoritmo "L01H"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos santos
// Descrição   : Calcular o volume de uma caixa retângular.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

raio:inteiro
altura:real
volume:real

Inicio

escreval("Digite o valor do raio desta caixa")
leia (raio)
escreval("Digite o valor correspondete a altura da caixa")
leia (altura)

volume<-pi*(raio^2)*altura

escreval("O volume de sua caixa retângular é de ", volume:5:2)




Fimalgoritmo