Algoritmo "l01I"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcular e mostrar a diferença de um número para outro.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

a,b:inteiro
menos:inteiro

Inicio

escreval("Digite o valor para a letra A")
leia (a)
escreval("Digite o valor para a letra B")
leia (b)

se  a>b entao
menos<- a-b
senao
se b>a  entao
menos<-b-a
fimse
fimse

escreval("a diferença do valor ",a, " para o valor ", b, " é de: ", menos)




Fimalgoritmo