Algoritmo "L01J"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentação do valor da conversão em real de um valor lido
// em dólar.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

cotacao,quantidade,valordecambio:real

Inicio

escreval("Digite o valor da cotação do dólar neste instante")
leia (cotacao)
escreval("Digite a quantidade de dólares aos quais deseja converter em Real")
leia (quantidade)

valordecambio<-quantidade*cotacao

escreval("O valor em reais ao qual você tem convertido do dólar é de ",valordecambio:4:2)




Fimalgoritmo