Algoritmo "L01K"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentação do valor da conversão em dólar de um valor lido
//em real
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

cotacao,quantidade,valordecambio:real

Inicio

escreval("Digite o valor da cotação do dólar neste instante")
leia (cotacao)
escreval("Digite a quantidade de real aos quais deseja converter em dólar")
leia (quantidade)

valordecambio<-quantidade/cotacao

escreval("O valor em dólares ao qual você tem convertido do real é de ",valordecambio:4:2)




Fimalgoritmo