Algoritmo "L01L"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Soma dos três valores elevados ao qaudrado.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

a,b,c:real
soma:real


Inicio

escreval("Digite o valor para A")
leia (a)
escreval("Digite o valor para B")
leia (b)
escreval("Digite o valor para C")
leia (c)

soma<-(a^2)+(b^2)+(c^2)

escreval("A soma dos quadrados dos três valores lidos é de: ", soma)



Fimalgoritmo