Algoritmo "L03M"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Soma do resultado final dos três valores somados elevados ao qaudrado.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 26/09/2026

Var

a,b,c:real
soma:real


Inicio

escreval("Digite o valor para A")
leia (a)
escreval("Digite o valor para B")
leia (b)
escreval("Digite o valor para C")
leia (c)

soma<- (a+b+C)^2

escreval("O quadrado da soma dos trêS valores é de: ", soma)



Fimalgoritmo