Algoritmo "LO3A"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Descobrir a tabuada de 1 a 10, referênte a qualquer número que digitar.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/09/2026
Var
numero:inteiro
contadora:inteiro
multiplicacao:inteiro

Inicio

escreval("Digite um número para descobrir a multiplicação dele de 1 ao 10")
leia(numero)

contadora<-1
multiplicacao<-0

enquanto contadora<11 faca
multiplicacao<-numero*contadora
escreval(numero,"x", contadora, "=",multiplicacao)
contadora<-contadora+1
fimenquanto

Fimalgoritmo