Algoritmo "LO3B"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar o total das somas obitidas dos
//cem primeiros números somados.
// Autor(a)    : Agnes Pereira rodrigues Catarino
// Data atual  : 26/09/2026
Var
contadora:inteiro
somadora:inteiro

Inicio


contadora<-1
somadora<-0

enquanto contadora<101 faca
somadora<-somadora+contadora
contadora<-contadora+1
fimenquanto
escreval("A soma dos números inteiros será: ", somadora)

Fimalgoritmo