Algoritmo "LO3C"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Resultado do total da somatoria dos valores existentes de 1 a 500.
// Autor(a)    : Agnes Pereira rodrigues Catarino
// Data atual  : 26/09/2026
Var
contadora:inteiro
somadora:inteiro

Inicio


contadora<-1
somadora<-0

enquanto contadora<501 faca
somadora<-somadora+contadora
contadora<-contadora+2
fimenquanto
escreval("A soma dos números inteiros será: ", somadora)

Fimalgoritmo