Algoritmo "LO3D"
// Disciplina   : [Linguagem e Lógica de Programação com javaScript]
// Professor   : Jailson Costa do Santos
// Descrição   : Mostrar os números impares de 0 a 20.
// Autor(a)    : Agnes Pereira rodrigues Catarino
// Data atual  : 26/09/2026
Var
// Seção de Declarações das variáveis 
contadora:inteiro
somadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

contadora<-0
somadora<-0

enquanto contadora<21 faca
se contadora % 2=1 entao
escreval (contadora)
somadora<-somadora+contadora
fimse
contadora<-contadora+1
fimenquanto

Fimalgoritmo