Algoritmo "LO3E"
// Disciplina   : [Linguagem e Lógica de Programação com javaScript]
// Professor   : Jailson Costa do Santos
// Descrição   : Realizando potenciação sem o "^", de 0 a 15.
// Autor(a)    : Agnes Pereira rodrigues Catarino
// Data atual  : 26/09/2026
Var

numero:inteiro
potencia:real
contador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

numero<-3
contador<-0
potencia<-1

enquanto contador<16 faca
escreval(numero, "^", contador, "= ",potencia )
potencia<-potencia*numero
contador<-contador+1
fimenquanto



Fimalgoritmo