Algoritmo "LO3G"
// Disciplina   : [Linguagem e Lógica de Programação com javaScript]
// Professor   : Jailson Costa do Santos
// Descrição   : Escreva um programa que apresente a série de Fibonacci
//até o décimo quinto termo
// Autor(a)    : Agnes Pereira rodrigues Catarino
// Data atual  : 26/09/2026

Var

numeroanterior,atual, proximonumero,contador:inteiro

Inicio

numeroanterior<-1
atual<-0
contador<-1

enquanto contador<16 faca
proximonumero<-numeroanterior+atual
escreval(contador," ºnúmero=", proximonumero)

numeroanterior<-atual
atual<-proximonumero
contador<-contador+1
fimenquanto


Fimalgoritmo
