Algoritmo "LO3H"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Convertendo Celcius em Fahrenhei, de 10 em 10 graus.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 27/09/2026

Var
celcius:inteiro
fahrenheit:real


Inicio

celcius<-10

enquanto celcius<101 faca
fahrenheit<- (9* celcius +160)/5
escreval("O valor do celcius ","°",celcius," em fahrenheit será de: ","°",fahrenheit)
celcius<-celcius+10
fimenquanto


Fimalgoritmo