Algoritmo "L04A"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Apresentar os números ao quadrado de 15 ao 200.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 27/09/2026

Var

numero, aoquadrado:inteiro

Inicio


numero<-15
repita
aoquadrado<-numero*numero
escreval("Este ", numero, " ao quadrado é ", aoquadrado)
numero<-numero+1
ate numero>200


Fimalgoritmo