Algoritmo "l04B"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Soma dos números pares de 1 ao 100.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 27/09/2026

Var

somadora, contadora:inteiro

Inicio

contadora<-0
somadora<-1

repita
somadora<-somadora+contadora
contadora<-contadora+2

ate contadora>500

escreval("A soma dos números pares de 1 ao 100, são: ", somadora)


Fimalgoritmo