Algoritmo "LO4C"
// Disciplina   : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Jailson Costa do Santos
// Descrição   : Apresentar os valores divisiveis por 4 de 1 ao 200.
// Autor(a)    : Agnes Pereira Rodrigues Catarino
// Data atual  : 27/09/2026
Var
// Seção de Declarações das variáveis
contador:inteiro


Inicio

contador<-1

repita
se contador % 4 =0 entao
escreval(contador)
fimse
contador<-contador+1
ate contador>200



Fimalgoritmo